name: development

on:
  push:
    branches:
      - development

env:
  FAITH_GIVING_API: "faith-giving-api"
  FAITH_GIVING_UI: "faith-giving-ui"
  DB_HOST: ${{DB_HOST}}
  DB_PORT: ${{DB_PORT}}
  DB_USER: ${{DB_USER}}
  DB_PASSWORD: ${{DB_PASSWORD}}
      
jobs:
  build-test:
    permissions: write-all
    name: connectdb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check affected projects
        id: affected-projects
        run: |
          affected_projects=$(npx nx print-affected --base=${{ github.event.before }} --head=${{ github.sha }} --select=projects)
          echo "::set-output name=projects::$affected_projects"
          echo "Workspace: ${{ github.workspace }}"

      - name: Run Command
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_API)
        run: |
          npx nx run faith-giving-api:typeorm:run-migrations