name: Prod

on:
  push:
    branches:
      - master

env:
  FAITH_GIVING_API: "faith-giving-api"
  FAITH_GIVING_UI: "faith-giving-ui"

jobs:
  build:
    permissions: write-all
    name: Building Applications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Nx CLI
        run: npm install -g @nrwl/cli

      - uses: nrwl/nx-set-shas@v3
        with: 
          main-branch-name: 'master'
          
      - run: npm i --force
      - run: npm --prefix api-gateway --omit=dev -f install

      - run: npx nx affected -t build --parallel=3

      - name: Check affected projects
        id: affected-projects
        run: |
          affected_projects=$(npx nx print-affected --base=${{ github.event.before }} --head=${{ github.sha }} --select=projects)
          echo "::set-output name=projects::$affected_projects"
          echo "Workspace: ${{ github.workspace }}"
      - name: Upload Faith-Giving-Api Files
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_API)
        uses: actions/upload-artifact@v3
        with:
          name: faith_giving_api
          path: dist/apps/faith-giving-api

      - name: Upload Faith-Giving-UI Files
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_UI)
        uses: actions/upload-artifact@v3
        with:
          name: faith_giving_ui
          path: dist/apps/faith-giving-ui

  deploy:
    permissions: write-all
    name: Deploy Applications
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Nx CLI
        run: npm install -g @nrwl/cli

      - uses: nrwl/nx-set-shas@v3
        with: 
          main-branch-name: 'master'
          
      - run: npm i --force

      - name: Check affected projects
        id: affected-projects
        run: |
          affected_projects=$(npx nx print-affected --base=${{ github.event.before }} --head=${{ github.sha }} --select=projects)
          echo "::set-output name=projects::$affected_projects"
      - name: Download API Files
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_API)
        uses: actions/download-artifact@v2
        with:
          name: faith_giving_api
          path: api_project

      - name: Copy Backend to Server
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_UI)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/projects/faith-service-api
            mv /root/projects/faith-giving-api/.env /root/projects/faith-giving-api-env/.env
            rm -rf /root/projects/faith-giving-api/*
            cp -r api_project/* /root/projects/faith-giving-api/
            mv /root/projects/faith-giving-api-env/.env /root/projects/faith-giving-ui/.env
            
      - name: Restart API
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_API)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 restart faith-giving-api

      - name: Download UI Files
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_UI)
        uses: actions/download-artifact@v2
        with:
          name: faith_giving_ui
          path: ui_project

      - name: Copy UI to Server
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_UI)
        uses: garygrossgarten/github-action-scp@release
        with: 
          local: ui_project
          remote: /root/projects/faith-giving-ui
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          rmRemote: true
          concurrency: 2
          recursive: true
          atomicPut: true
          port: 22
          verbose: true

      - name: Copy API to Server_web dir
        if: contains(steps.affected-projects.outputs.projects, env.FAITH_GIVING_UI)
        uses: garygrossgarten/github-action-scp@release
        with: 
          local: ui_project
          remote: /var/www/faith-giving
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          rmRemote: true
          concurrency: 2
          recursive: true
          atomicPut: true
          port: 22
          verbose: true
